# Copyright Dave Verwer, Sven A. Schmidt, and other contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Nightly Audit

# on: 
#   workflow_dispatch:
#   schedule:
#     - cron: '0 2 * * *'
on:
    push:
      # branches: [ main ]
    pull_request:
      branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run_nightly:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Get swift version
        run: swift --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build validator
        run: |
          swift build

      - name: Check redirects
        run: ./check-redirects.sh

      - name: Check dependencies
        run: ./check-dependencies.sh
