name: Nightly Audit

# on: 
#   workflow_dispatch:
#   schedule:
#     - cron: '0 2 * * *'
on:
    push:
      # branches: [ main ]
    pull_request:
      branches: [ main ]
  
jobs:
  run_nightly:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check redirects
      run: ./run-redirects.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.5.app
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check dependencies
      run: ./run-dependencies.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.5.app
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
